
---
- name: Install kubectl on Ubuntu
  hosts: all
  become: yes

  tasks:

    - name: Download kubectl v1.37.0
      get_url:
        url: https://dl.k8s.io/release/v1.37.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verify kubectl
      command: kubectl version --client
      register: kubectl_version
      changed_when: false

    - name: Display kubectl version
      debug:
        var: kubectl_version.stdout

